### ISSUE TITLE
'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by qinzhu** [Murali-group/BoolODE#12]
Hi,

I was trying the example data with following command:
`python boolode.py --config config-files/example-config.yaml`

But got following error:
```
Global settings:
----------------
        model_dir: data
        output_dir: Debug
        do_simulations: True
        do_post_processing: True
        modeltype: hill
Creating output folders
Debug/dyn-linear-1 does not exist, creating it...
Starting simulations
Sampling parameter values
Using std=0.5
Debug/dyn-linear-1/simulations does not exist, creating it...
Starting simulations
Simulations took 4.297 s
starting to concat files
100%|█████████████████████████████████████████████████████████████████| 500/500 [00:29<00:00, 17.03it/s]
Concating files took 29.38 s
Requested nClusters=1, not performing k-means clustering
Generating input files for pipline...
1. refNetwork
2. PseudoTime.csv
Dataset too large.
Sampling 500 cells, one from each simulated trajectory.
Input file generation took 2.76 s
BoolODE.py took 36.71s
Starting post processing
Generating Samples...
Traceback (most recent call last):
  File "boolode.py", line 39, in <module>
    main()
  File "boolode.py", line 34, in main
    boolodejobs.execute_jobs()
  File "/kimdata/zhuqin/MEDIVH/BoolODE/BoolODE/__init__.py", line 132, in execute_jobs
    self.do_post_processing()
  File "/kimdata/zhuqin/MEDIVH/BoolODE/BoolODE/__init__.py", line 154, in do_post_processing
    gsamp['sample_size'] = self.jobs[alljobs[0]]['num_cells']
TypeError: 'dict_keys' object is not subscriptable
```

Some other networks seem to run fine, e.g., `python boolode.py --config config-files/config.yaml`.
I used the conda env created by Beeline, ". setupAnacondaVENV.sh"
Could you help on this? Thanks!

**Comment by amoghpj** [comment]
Hi, thank you for trying out BoolODE. The latest commit c6467a4 fixes these errors. Can you please pull the latest version of master and run the command again? Please let me know if there are other errors!

**Comment by amoghpj** [comment]
Closing this issue for now.
