### ISSUE TITLE
BoolODE errors when running jobs in parallel

### ISSUE THREAD

**Issue by yutuyt01** [Murali-group/BoolODE#23]
When running jobs in parallel, the following error and stack trace occurs:

```
Traceback (most recent call last):
  File "C:\Users\shang\anaconda3\envs\Beeline37\lib\multiprocessing\process.py", line 297, in _bootstrap self.run()
  File "C:\Users\shang\anaconda3\envs\Beeline37\lib\multiprocessing\process.py", line 99, in run self._target(*self._args, **self._kwargs)
  File "C:\Users\shang\anaconda3\envs\Beeline37\lib\multiprocessing\pool.py", line 110, in worker task = get()
  File "C:\Users\shang\anaconda3\envs\Beeline37\lib\multiprocessing\queues.py", line 354, in get return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'model'
```

Operating on Windows 11.
I have all dependencies installed, but it seems that this error stemmed from the multiprocessing library itself.
Setting do_parallel in config.yaml to false for each job solves the issue.

**Comment by yutuyt01** [comment]
Error only applies to Windows systems
